"""add valor_mao_obra_avulso to ordens_servico

Revision ID: 236597bca920
Revises: 5fa3d6772ab3
Create Date: 2026-02-23 23:24:36.605797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236597bca920'
down_revision = '5fa3d6772ab3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordens_servico', sa.Column('valor_mao_obra_avulso', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_index('ix_ordens_servico_cliente_id', table_name='ordens_servico')
    op.drop_index('ix_ordens_servico_veiculo_id', table_name='ordens_servico')
    op.drop_index('ux_ordens_servico_numero', table_name='ordens_servico')
    op.drop_constraint('fk_ordens_servico_cliente', 'ordens_servico', type_='foreignkey')
    op.drop_constraint('fk_ordens_servico_veiculo', 'ordens_servico', type_='foreignkey')
    op.drop_constraint('perfis_nome_key', 'perfis', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('perfis_nome_key', 'perfis', ['nome'])
    op.create_foreign_key('fk_ordens_servico_veiculo', 'ordens_servico', 'veiculos', ['veiculo_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_ordens_servico_cliente', 'ordens_servico', 'clientes', ['cliente_id'], ['id'], ondelete='RESTRICT')
    op.create_index('ux_ordens_servico_numero', 'ordens_servico', ['numero'], unique=False)
    op.create_index('ix_ordens_servico_veiculo_id', 'ordens_servico', ['veiculo_id'], unique=False)
    op.create_index('ix_ordens_servico_cliente_id', 'ordens_servico', ['cliente_id'], unique=False)
    op.drop_column('ordens_servico', 'valor_mao_obra_avulso')
    # ### end Alembic commands ###