"""add_configuracoes_table

Revision ID: 32a20b8adc4d
Revises: 12d83feea809
Create Date: 2025-10-15 22:39:12.326047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32a20b8adc4d'
down_revision = '12d83feea809'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracoes_chave'), 'configuracoes', ['chave'], unique=True)
    op.create_index(op.f('ix_configuracoes_id'), 'configuracoes', ['id'], unique=False)
    op.alter_column('movimentos_estoque', 'quantidade',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('movimentos_estoque', 'motivo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('ordens_servico', 'data_abertura',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ordens_servico', 'data_abertura',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('movimentos_estoque', 'motivo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('movimentos_estoque', 'quantidade',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=3),
               existing_nullable=False)
    op.drop_index(op.f('ix_configuracoes_id'), table_name='configuracoes')
    op.drop_index(op.f('ix_configuracoes_chave'), table_name='configuracoes')
    op.drop_table('configuracoes')
    # ### end Alembic commands ###