"""reformular_ordem_servico_nova_estrutura

Revision ID: 7f894655893d
Revises: af8e4f151f4d
Create Date: 2025-09-23 17:20:44.860795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f894655893d'
down_revision = 'af8e4f151f4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_ordem', sa.Column('produto_id', sa.Integer(), nullable=True))
    op.add_column('itens_ordem', sa.Column('desconto_item', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0.00'))
    op.drop_constraint('itens_ordem_item_estoque_id_fkey', 'itens_ordem', type_='foreignkey')
    op.create_foreign_key(None, 'itens_ordem', 'produtos', ['produto_id'], ['id'])
    op.drop_column('itens_ordem', 'item_estoque_id')
    
    # Adicionar colunas com valores padrão
    op.add_column('ordens_servico', sa.Column('tipo_ordem', sa.String(length=20), nullable=True, server_default='SERVICO'))
    op.add_column('ordens_servico', sa.Column('descricao_servico', sa.Text(), nullable=True))
    op.add_column('ordens_servico', sa.Column('data_ordem', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ordens_servico', sa.Column('valor_servico', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0.00'))
    op.add_column('ordens_servico', sa.Column('valor_subtotal', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0.00'))
    op.add_column('ordens_servico', sa.Column('valor_desconto', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0.00'))
    op.add_column('ordens_servico', sa.Column('percentual_desconto', sa.Numeric(precision=5, scale=2), nullable=True, server_default='0.00'))
    op.add_column('ordens_servico', sa.Column('tipo_desconto', sa.String(length=20), nullable=True, server_default='TOTAL'))
    
    # Alterar descricao_problema para nullable
    op.alter_column('ordens_servico', 'descricao_problema',
               existing_type=sa.TEXT(),
               nullable=True)
    
    # Atualizar valores padrão e tornar NOT NULL depois
    op.execute("UPDATE ordens_servico SET tipo_ordem = 'SERVICO' WHERE tipo_ordem IS NULL")
    op.execute("UPDATE ordens_servico SET valor_servico = 0.00 WHERE valor_servico IS NULL")
    op.execute("UPDATE ordens_servico SET valor_subtotal = valor_total WHERE valor_subtotal IS NULL")
    op.execute("UPDATE ordens_servico SET valor_desconto = desconto WHERE valor_desconto IS NULL")
    op.execute("UPDATE ordens_servico SET percentual_desconto = 0.00 WHERE percentual_desconto IS NULL")
    op.execute("UPDATE ordens_servico SET tipo_desconto = 'TOTAL' WHERE tipo_desconto IS NULL")
    op.execute("UPDATE itens_ordem SET desconto_item = 0.00 WHERE desconto_item IS NULL")
    
    # Tornar NOT NULL após popular valores
    op.alter_column('ordens_servico', 'tipo_ordem', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ordens_servico', 'descricao_problema',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('ordens_servico', 'tipo_desconto')
    op.drop_column('ordens_servico', 'percentual_desconto')
    op.drop_column('ordens_servico', 'valor_desconto')
    op.drop_column('ordens_servico', 'valor_subtotal')
    op.drop_column('ordens_servico', 'valor_servico')
    op.drop_column('ordens_servico', 'data_ordem')
    op.drop_column('ordens_servico', 'descricao_servico')
    op.drop_column('ordens_servico', 'tipo_ordem')
    op.add_column('itens_ordem', sa.Column('item_estoque_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'itens_ordem', type_='foreignkey')
    op.create_foreign_key('itens_ordem_item_estoque_id_fkey', 'itens_ordem', 'produtos', ['item_estoque_id'], ['id'])
    op.drop_column('itens_ordem', 'desconto_item')
    op.drop_column('itens_ordem', 'produto_id')
    # ### end Alembic commands ###