"""Add frontend integration fields

Revision ID: af8e4f151f4d
Revises: 
Create Date: 2025-09-17 02:18:15.288566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af8e4f151f4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('total_clientes', sa.Integer(), nullable=True),
    sa.Column('total_veiculos', sa.Integer(), nullable=True),
    sa.Column('total_pecas_estoque', sa.Integer(), nullable=True),
    sa.Column('ordens_abertas', sa.Integer(), nullable=True),
    sa.Column('ordens_hoje', sa.Integer(), nullable=True),
    sa.Column('receita_mensal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('receita_diaria', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('crescimento_mensal', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('servicos_realizados', sa.Integer(), nullable=True),
    sa.Column('pecas_vendidas', sa.Integer(), nullable=True),
    sa.Column('alertas_estoque', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_stats_id'), 'dashboard_stats', ['id'], unique=False)
    op.create_table('manutencoes_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('km_realizada', sa.Integer(), nullable=False),
    sa.Column('data_realizada', sa.Date(), nullable=False),
    sa.Column('km_proxima', sa.Integer(), nullable=True),
    sa.Column('data_proxima', sa.Date(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manutencoes_historico_id'), 'manutencoes_historico', ['id'], unique=False)
    op.add_column('clientes', sa.Column('telefone2', sa.String(length=20), nullable=True))
    op.add_column('clientes', sa.Column('whatsapp', sa.String(length=20), nullable=True))
    op.add_column('clientes', sa.Column('numero', sa.String(length=20), nullable=True))
    op.add_column('clientes', sa.Column('complemento', sa.String(length=100), nullable=True))
    op.add_column('clientes', sa.Column('bairro', sa.String(length=100), nullable=True))
    op.add_column('clientes', sa.Column('tipo', sa.String(length=2), nullable=False))
    op.add_column('clientes', sa.Column('nome_fantasia', sa.String(length=255), nullable=True))
    op.add_column('clientes', sa.Column('razao_social', sa.String(length=255), nullable=True))
    op.add_column('clientes', sa.Column('contato_responsavel', sa.String(length=255), nullable=True))
    op.add_column('clientes', sa.Column('rg_ie', sa.String(length=20), nullable=True))
    op.drop_index(op.f('ix_clientes_cpf_cnpj'), table_name='clientes')
    op.create_index(op.f('ix_clientes_cpf_cnpj'), 'clientes', ['cpf_cnpj'], unique=False)
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=False)
    op.drop_column('clientes', 'celular')
    op.add_column('itens_ordem', sa.Column('item_estoque_id', sa.Integer(), nullable=True))
    op.add_column('itens_ordem', sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('itens_ordem', sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('itens_ordem', sa.Column('observacoes', sa.Text(), nullable=True))
    op.drop_constraint(op.f('itens_ordem_produto_id_fkey'), 'itens_ordem', type_='foreignkey')
    op.create_foreign_key(None, 'itens_ordem', 'produtos', ['item_estoque_id'], ['id'])
    op.drop_column('itens_ordem', 'preco_unitario')
    op.drop_column('itens_ordem', 'preco_total')
    op.drop_column('itens_ordem', 'produto_id')
    op.add_column('movimentos_estoque', sa.Column('item_id', sa.Integer(), nullable=False))
    op.add_column('movimentos_estoque', sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('movimentos_estoque', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.add_column('movimentos_estoque', sa.Column('usuario_nome', sa.String(length=255), nullable=True))
    op.add_column('movimentos_estoque', sa.Column('ordem_servico_id', sa.Integer(), nullable=True))
    op.add_column('movimentos_estoque', sa.Column('data_movimentacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('movimentos_estoque', 'motivo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(op.f('movimentos_estoque_produto_id_fkey'), 'movimentos_estoque', type_='foreignkey')
    op.create_foreign_key(None, 'movimentos_estoque', 'produtos', ['item_id'], ['id'])
    op.create_foreign_key(None, 'movimentos_estoque', 'ordens_servico', ['ordem_servico_id'], ['id'])
    op.drop_column('movimentos_estoque', 'documento')
    op.drop_column('movimentos_estoque', 'data_movimento')
    op.drop_column('movimentos_estoque', 'produto_id')
    op.add_column('ordens_servico', sa.Column('descricao_problema', sa.Text(), nullable=False))
    op.add_column('ordens_servico', sa.Column('prioridade', sa.String(length=20), nullable=True))
    op.add_column('ordens_servico', sa.Column('data_prevista', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ordens_servico', sa.Column('valor_mao_obra', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('ordens_servico', sa.Column('valor_pecas', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('ordens_servico', sa.Column('funcionario_responsavel', sa.String(length=255), nullable=True))
    op.add_column('ordens_servico', sa.Column('tempo_estimado_horas', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('ordens_servico', sa.Column('tempo_gasto_horas', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('ordens_servico', sa.Column('aprovado_cliente', sa.Boolean(), nullable=True))
    op.alter_column('ordens_servico', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.drop_column('ordens_servico', 'valor_produtos')
    op.drop_column('ordens_servico', 'defeito_reclamado')
    op.drop_column('ordens_servico', 'valor_servicos')
    op.drop_column('ordens_servico', 'servicos_executados')
    op.drop_column('ordens_servico', 'valor_final')
    op.add_column('produtos', sa.Column('categoria', sa.String(length=100), nullable=True))
    op.add_column('produtos', sa.Column('quantidade_atual', sa.Integer(), nullable=True))
    op.add_column('produtos', sa.Column('quantidade_minima', sa.Integer(), nullable=True))
    op.add_column('produtos', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('produtos', sa.Column('data_ultima_movimentacao', sa.DateTime(timezone=True), nullable=True))
    op.add_column('produtos', sa.Column('tipo_ultima_movimentacao', sa.String(length=10), nullable=True))
    op.drop_column('produtos', 'estoque_atual')
    op.drop_column('produtos', 'estoque_minimo')
    op.add_column('veiculos', sa.Column('chassis', sa.String(length=50), nullable=True))
    op.add_column('veiculos', sa.Column('renavam', sa.String(length=20), nullable=True))
    op.drop_constraint(op.f('veiculos_chassi_key'), 'veiculos', type_='unique')
    op.create_unique_constraint(None, 'veiculos', ['chassis'])
    op.drop_column('veiculos', 'chassi')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('veiculos', sa.Column('chassi', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'veiculos', type_='unique')
    op.create_unique_constraint(op.f('veiculos_chassi_key'), 'veiculos', ['chassi'], postgresql_nulls_not_distinct=False)
    op.drop_column('veiculos', 'renavam')
    op.drop_column('veiculos', 'chassis')
    op.add_column('produtos', sa.Column('estoque_minimo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('produtos', sa.Column('estoque_atual', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('produtos', 'tipo_ultima_movimentacao')
    op.drop_column('produtos', 'data_ultima_movimentacao')
    op.drop_column('produtos', 'status')
    op.drop_column('produtos', 'quantidade_minima')
    op.drop_column('produtos', 'quantidade_atual')
    op.drop_column('produtos', 'categoria')
    op.add_column('ordens_servico', sa.Column('valor_final', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('ordens_servico', sa.Column('servicos_executados', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ordens_servico', sa.Column('valor_servicos', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('ordens_servico', sa.Column('defeito_reclamado', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ordens_servico', sa.Column('valor_produtos', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.alter_column('ordens_servico', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('ordens_servico', 'aprovado_cliente')
    op.drop_column('ordens_servico', 'tempo_gasto_horas')
    op.drop_column('ordens_servico', 'tempo_estimado_horas')
    op.drop_column('ordens_servico', 'funcionario_responsavel')
    op.drop_column('ordens_servico', 'valor_pecas')
    op.drop_column('ordens_servico', 'valor_mao_obra')
    op.drop_column('ordens_servico', 'data_prevista')
    op.drop_column('ordens_servico', 'prioridade')
    op.drop_column('ordens_servico', 'descricao_problema')
    op.add_column('movimentos_estoque', sa.Column('produto_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('movimentos_estoque', sa.Column('data_movimento', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('movimentos_estoque', sa.Column('documento', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'movimentos_estoque', type_='foreignkey')
    op.drop_constraint(None, 'movimentos_estoque', type_='foreignkey')
    op.create_foreign_key(op.f('movimentos_estoque_produto_id_fkey'), 'movimentos_estoque', 'produtos', ['produto_id'], ['id'])
    op.alter_column('movimentos_estoque', 'motivo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('movimentos_estoque', 'data_movimentacao')
    op.drop_column('movimentos_estoque', 'ordem_servico_id')
    op.drop_column('movimentos_estoque', 'usuario_nome')
    op.drop_column('movimentos_estoque', 'usuario_id')
    op.drop_column('movimentos_estoque', 'valor_total')
    op.drop_column('movimentos_estoque', 'item_id')
    op.add_column('itens_ordem', sa.Column('produto_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('itens_ordem', sa.Column('preco_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('itens_ordem', sa.Column('preco_unitario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'itens_ordem', type_='foreignkey')
    op.create_foreign_key(op.f('itens_ordem_produto_id_fkey'), 'itens_ordem', 'produtos', ['produto_id'], ['id'])
    op.drop_column('itens_ordem', 'observacoes')
    op.drop_column('itens_ordem', 'valor_total')
    op.drop_column('itens_ordem', 'valor_unitario')
    op.drop_column('itens_ordem', 'item_estoque_id')
    op.add_column('clientes', sa.Column('celular', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=True)
    op.drop_index(op.f('ix_clientes_cpf_cnpj'), table_name='clientes')
    op.create_index(op.f('ix_clientes_cpf_cnpj'), 'clientes', ['cpf_cnpj'], unique=True)
    op.drop_column('clientes', 'rg_ie')
    op.drop_column('clientes', 'contato_responsavel')
    op.drop_column('clientes', 'razao_social')
    op.drop_column('clientes', 'nome_fantasia')
    op.drop_column('clientes', 'tipo')
    op.drop_column('clientes', 'bairro')
    op.drop_column('clientes', 'complemento')
    op.drop_column('clientes', 'numero')
    op.drop_column('clientes', 'whatsapp')
    op.drop_column('clientes', 'telefone2')
    op.drop_index(op.f('ix_manutencoes_historico_id'), table_name='manutencoes_historico')
    op.drop_table('manutencoes_historico')
    op.drop_index(op.f('ix_dashboard_stats_id'), table_name='dashboard_stats')
    op.drop_table('dashboard_stats')
    # ### end Alembic commands ###